baseURL = "https://yuppychen.github.io/fugong/"
languageCode = "zh-CN"
title = "fugong's Blog"
theme = "hyde"
disqusShortname = ""
hasCJKLanguage = true
enableEmoji = true

[permalinks]
  posts = "/:filename/"

[Menus]
  main = [
      {Name = "Archives", URL = "https://yuppychen.github.io/fugong/posts/"},
      {Name = "Tags", URL = "https://yuppychen.github.io/fugong/tags/"},
      {Name = "Books", URL = "https://yuppychen.github.io/fugong/books/"},
      {Name = "Movies", URL = "https://yuppychen.github.io/fugong/movies/"},
      {Name = "Photos", URL = "https://yuppychen.github.io/fugong/photos/"}
  ]

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # description abou this website
  description = "There is only one thing in the world worse than being talked about, and that is not being talked about."

[params.valine]
  enable = true
    appId = ''
    appKey = ''
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true